export const CONNECT_START = "CONNECT_START";
export const CONNECT_SUCCESS = "CONNECT_SUCCESS";
export const CONNECT_ERROR = "CONNECT_ERROR";

export const DISCONNECT_START = "DISCONNECT_START";
export const DISCONNECT_SUCCESS = "DISCONNECT_SUCCESS";
export const DISCONNECT_ERROR = "DISCONNECT_ERROR";

export const METHOD_CALL_START = "METHOD_CALL_START";
export const METHOD_CALL_SUCCESS = "METHOD_CALL_SUCCESS";
export const METHOD_CALL_ERROR = "METHOD_CALL_ERROR";

export const SUBSCRIPTION_START = "SUBSCRIPTION_START";
export const SUBSCRIPTION_SUCCESS = "SUBSCRIPTION_SUCCESS";
export const SUBSCRIPTION_ERROR = "SUBSCRIPTION_ERROR";

export const SCENARIO_START = "SCENARIO_START";
export const SCENARIO_END = "SCENARIO_END";
